# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.url import URL  # noqa: F401,E501
from swagger_server import util


class URLs(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, url: URL=None):  # noqa: E501
        """URLs - a model defined in Swagger

        :param url: The url of this URLs.  # noqa: E501
        :type url: URL
        """
        self.swagger_types = {
            'url': URL
        }

        self.attribute_map = {
            'url': 'url'
        }
        self._url = url

    @classmethod
    def from_dict(cls, dikt) -> 'URLs':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The URLs of this URLs.  # noqa: E501
        :rtype: URLs
        """
        return util.deserialize_model(dikt, cls)

    @property
    def url(self) -> URL:
        """Gets the url of this URLs.


        :return: The url of this URLs.
        :rtype: URL
        """
        return self._url

    @url.setter
    def url(self, url: URL):
        """Sets the url of this URLs.


        :param url: The url of this URLs.
        :type url: URL
        """

        self._url = url
