# coding: utf-8

"""
    Tiny URL

    This is a sample TinyURL API server.  You can find out more about at piquednow.shopify.com. For this sample, you do not need any authorization  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: okunlola.olanre@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.url_api import UrlApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUrlApi(unittest.TestCase):
    """UrlApi unit test stubs"""

    def setUp(self):
        self.api = api.url_api.UrlApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_url(self):
        """Test case for delete_url

        Deletes an encoded url  # noqa: E501
        """
        pass

    def test_encode_url(self):
        """Test case for encode_url

        Encode a new url  # noqa: E501
        """
        pass

    def test_get_all_urls(self):
        """Test case for get_all_urls

        Gets the list of all encoded urls  # noqa: E501
        """
        pass

    def test_get_long_url_by_id(self):
        """Test case for get_long_url_by_id

        Extract a URL entry by the given tiny URL  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
