# coding: utf-8

"""
    Tiny URL

    This is a sample TinyURL API server.  You can find out more about at piquednow.shopify.com. For this sample, you do not need any authorization  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: okunlola.olanre@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.api_response import ApiResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestApiResponse(unittest.TestCase):
    """ApiResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiResponse(self):
        """Test ApiResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.api_response.ApiResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
