# coding: utf-8

"""
    Tiny URL

    This is a sample TinyURL API server.  You can find out more about at piquednow.shopify.com. For this sample, you do not need any authorization  # noqa: E501
    Hello World I'm a Wild GIRL!
    OpenAPI spec version: 1.0.0
    Contact: okunlola.olanre@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.ur_ls import URLs  # noqa: E501
from swagger_client.rest import ApiException


class TestURLs(unittest.TestCase):
    """URLs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testURLs(self):
        """Test URLs"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.ur_ls.URLs()  # noqa: E501
        pass

    def testBreaks(self):
        pass

if __name__ == '__main__':
    unittest.main()
