# coding: utf-8

"""
    Tiny URL

    This is a sample TinyURL API server.  You can find out more about at piquednow.shopify.com. For this sample, you do not need any authorization  # noqa: E501
    Hello World
    OpenAPI spec version: 1.0.0
    Contact: okunlola.olanre@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.url import URL  # noqa: E501
from swagger_client.rest import ApiException


class TestURL(unittest.TestCase):
    """URL unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testURL(self):
        """Test URL"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.url.URL()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
